repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.10
        args: ["--diff"]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: ["add", "fix", "update", "remove", "security"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        name: Format Markdown files (prettier)
        files: '\.md$'
      - id: prettier
        name: Format JSON files (prettier)
        files: '\.json$'
      - id: prettier
        name: Format YAML files (prettier)
        files: '\.ya?ml$'
      - id: prettier
        name: Format TOML files (prettier)
        files: '\.toml$'
